# Versioning System
PRODUCT_VERSION_MAJOR = 5.0
PRODUCT_VERSION_MINOR = ALPHA
PRODUCT_VERSION_MAINTENANCE = 1.0
ifdef FOS_BUILD_EXTRA
    FOS_POSTFIX := -$(SLIM_BUILD_EXTRA)
endif
ifndef FOS_BUILD_TYPE
    FOS_BUILD_TYPE := HOMEMADE
    PLATFORM_VERSION_CODENAME := HOMEMADE
    FOS_POSTFIX := -$(shell date +"%Y%m%d-%H%M")
endif

# Set all versions
FOS_VERSION := FOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(FOS_BUILD_TYPE)$(FOS_POSTFIX)
FOS_MOD_VERSION := FOS-$(FOS_BUILD)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)-$(FOS_BUILD_TYPE)$(FOS_POSTFIX)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    fos.ota.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE) \
    ro.fos.version=$(SLIM_VERSION) \
    ro.modversion=$(SLIM_MOD_VERSION) \
    ro.fos.buildtype=$(SLIM_BUILD_TYPE)
